# Generated by Django 4.0.2 on 2022-03-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('lessonCount', models.IntegerField()),
                ('recommendedTime', models.IntegerField()),
                ('audience', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('type', models.IntegerField()),
                ('isTemplate', models.BooleanField()),
                ('taskType', models.IntegerField()),
                ('text', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=200)),
                ('releaseTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('recommendedTime', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('releaseTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=200)),
                ('entryTime', models.DateTimeField(null=True)),
                ('employeeType', models.CharField(max_length=20)),
                ('graduationTime', models.DateTimeField(null=True)),
                ('registrationTime', models.DateTimeField(auto_now=True)),
                ('superior', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=1000)),
                ('historicalMembers', models.IntegerField(default=0)),
                ('currentMembers', models.IntegerField(default=0)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isTeacher', models.BooleanField(default=False)),
                ('isHRBP', models.BooleanField(default=False)),
                ('isNew', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('contentCount', models.IntegerField()),
                ('beginTime', models.DateTimeField()),
                ('finishTime', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('audience', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('releaseTime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('beginTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField()),
                ('score', models.IntegerField(default=-1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.programtable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('beginTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lessontable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('finishedLessonCount', models.IntegerField(default=0)),
                ('beginTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField()),
                ('score', models.IntegerField(default=-1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contenttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.AddField(
            model_name='lessontable',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo'),
        ),
        migrations.AddField(
            model_name='lessontable',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contenttable'),
        ),
        migrations.CreateModel(
            name='CoursewareTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='')),
                ('uploadTime', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=200)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contenttable')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lessontable')),
            ],
        ),
        migrations.AddField(
            model_name='contenttable',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo'),
        ),
        migrations.AddField(
            model_name='contenttable',
            name='programId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programtable'),
        ),
    ]
