# Generated by Django 4.0.2 on 2022-04-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('recommendedTime', models.IntegerField()),
                ('audience', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('type', models.IntegerField()),
                ('isTemplate', models.BooleanField()),
                ('releaseTime', models.DateTimeField(auto_now_add=True)),
                ('lessonCount', models.IntegerField()),
                ('beginTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('taskType', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('recommendedTime', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('releaseTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=200)),
                ('joinDate', models.DateTimeField(null=True)),
                ('joinStatus', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=1000)),
                ('leader', models.CharField(max_length=50)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('employeeType', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isTeacher', models.BooleanField(default=False)),
                ('isHRBP', models.BooleanField(default=False)),
                ('isNew', models.BooleanField(default=False)),
                ('newcomerStartDate', models.DateTimeField(null=True)),
                ('newcomerIsGraduate', models.BooleanField(default=False)),
                ('newcomerGraduateDate', models.DateTimeField(null=True)),
                ('historicalMembers', models.IntegerField(default=0)),
                ('currentMembers', models.IntegerField(default=0)),
                ('teacherNominationDate', models.DateTimeField(null=True)),
                ('teacherExaminedStatus', models.IntegerField(default=0)),
                ('teacherExaminedDate', models.DateTimeField(null=True)),
                ('teacherIsDuty', models.BooleanField(default=False)),
                ('teacherDutyDate', models.DateTimeField(null=True)),
                ('teacherScore', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('contentCount', models.IntegerField()),
                ('recommendTime', models.IntegerField(null=True)),
                ('audience', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('releaseTime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgramTable',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('finishedContentCount', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('beginTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('score', models.IntegerField(default=-1)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProgramsAsAssigner', to='api.privateinfo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.programtable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProgramsAsUser', to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonTable',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('finished', models.BooleanField(default=False)),
                ('beginTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lessontable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentTable',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('finished', models.BooleanField(default=False)),
                ('userBeginTime', models.DateTimeField(auto_now_add=True)),
                ('userEndTime', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('isObligatory', models.BooleanField(default=True)),
                ('finishedLessonCount', models.IntegerField(default=0)),
                ('examUsedTime', models.IntegerField(default=-1)),
                ('score', models.IntegerField(default=-1)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ContentAsAssigner', to='api.privateinfo')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contenttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ContentAsUser', to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNewcomerTable',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('teacherScore', models.FloatField()),
                ('newcomerToTeacher', models.CharField(max_length=500)),
                ('newcomerScore', models.FloatField()),
                ('teacherToNewcomer', models.CharField(max_length=500)),
                ('newcomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AsNewcomer', to='api.privateinfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AsTeacher', to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramContentTable',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contenttable')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.programtable')),
            ],
        ),
        migrations.CreateModel(
            name='NewcomerRecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('commitTime', models.DateTimeField(auto_now=True)),
                ('newcomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RecodeNewcomer', to='api.privateinfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RecodeTeacher', to='api.privateinfo')),
            ],
        ),
        migrations.AddField(
            model_name='lessontable',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo'),
        ),
        migrations.AddField(
            model_name='lessontable',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contenttable'),
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CoursewareTable',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=200)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contenttable')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lessontable')),
            ],
        ),
        migrations.AddField(
            model_name='contenttable',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.privateinfo'),
        ),
        migrations.AddField(
            model_name='contenttable',
            name='programId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.programtable'),
        ),
    ]
