# Generated by Django 4.0.2 on 2022-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
