# Generated by Django 4.0.2 on 2022-03-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinfo',
            name='teacherDutyDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='teacherExaminedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='teacherNominationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='teacherScore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='programtable',
            name='recommendTime',
            field=models.IntegerField(null=True),
        ),
    ]
