# Generated by Django 4.0.2 on 2022-03-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontenttable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userlessontable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprogramtable',
            name='id',
        ),
        migrations.AddField(
            model_name='usercontenttable',
            name='relationID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlessontable',
            name='relationID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogramtable',
            name='relationID',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercontenttable',
            name='beginTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlessontable',
            name='beginTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprogramtable',
            name='beginTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProgramContentTable',
            fields=[
                ('relationID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contenttable')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.programtable')),
            ],
        ),
    ]
