# Generated by Django 4.0.2 on 2022-03-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinfo',
            name='entryTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='isHRBP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='isNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privateinfo',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
