# Generated by Django 4.0.2 on 2022-03-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_privateinfo_entrytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinfo',
            name='graduationTime',
            field=models.DateTimeField(null=True),
        ),
    ]
